### ISSUE TITLE
Can't pickle memoryview objects

### ISSUE THREAD

**Issue by mheppner** [noripyt/django-cachalot#115]
I'm getting this error after updating from 1.50 to 2.1.0:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 95, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 742, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 660, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 272, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 32, in inner
    return original(compiler, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 86, in inner
    cache_key, table_cache_keys)
  File "/usr/local/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 62, in _get_result_or_execute_query
    cache.set_many(to_be_set, cachalot_settings.CACHALOT_TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/backends/base.py", line 216, in set_many
    self.set(key, value, timeout=timeout, version=version)
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/backends/filebased.py", line 50, in set
    f.write(zlib.compress(pickle.dumps(value, pickle.HIGHEST_PROTOCOL)))
TypeError: can't pickle memoryview objects
```

- Python 3.6.5
- Django 2.0.3
- django-cachalot 2.1.0, file-based
- djangorestframework 3.7.7
- Postgres 9.6, PostGIS 2.4.4

The model it's getting this error on has a `django.contrib.postgres.fields.JSONField`. I know the docs mention the bug about using the file-based backend with Postgres range fields (which is now closed), but is this related? Are all Postgres fields unsupported?

My model also has a `django.contrib.gis.db.models.PolygonField`. I'm pretty sure we were using this field type, and the JSON field, without issues with django-cachalot 1.5.

**Comment by BertrandBordage** [comment]
It’s probably related to `PolygonField`, because it’s one of the only Django field types that can yield `memoryview`s when fetching data. `JSONField` cannot return it.

The error is caused because `memoryview` is inherently unpickable, it’s a pointer to a part of an object, not something with fixed bounds.

I’m pretty surprised if the reason is really caused by the upgrade from django-cachalot 1.5 to 2.0, because I didn’t change any of that logic in it. Without much digging, I’m pretty confident that it’s either:
- An error that was already in django-cachalot and you didn’t test exactly the same query with the same data with django-cachalot 1.5 & 2.0.
- An inconsistency with psycopg2 that changed one adaptater to yield `memoryview` instead of another type like `str`.
- A recent change introduced in Django 2.0

**So, could you test this please?**  Do the query that causes an error, downgrade Django to 1.11 while keeping django-cachalot and psycopg2 at the exact same versions, and run again the query. Tell me if the issue still occurs.

**Comment by narnikgamarnikus** [comment]
I have the same error.
I have the same requirements as @mheppner.

I can only add that I use [django-cities] (https://github.com/coderholic/django-cities) and any query with PointField causes this error.

**Comment by narnikgamarnikus** [comment]
> I have the same error and the same requirements as @mheppner.
> 
> I can only add that I use [django-cities](https://github.com/coderholic/django-cities)) and any query with PointField causes this error.

**Comment by mheppner** [comment]
I guess I was too quick to point the error at the upgrade from 1.5 to 2.0. It's very possible we weren't even using GIS fields prior to using Django 2.0+.

I'll close this, since it really isn't an issue. Do you want a pull for some documentation updates? I don't know too much about the internals of the GIS fields though.

**Comment by scherbakovx** [comment]
Hello! I just got this error after upgrading to Django 2.1 from 1.11. Are there any solutions? I use PolygonFields a lot in my project.

**Comment by scherbakovx** [comment]
![Sentry stack trace](https://user-images.githubusercontent.com/9437117/52045633-00106380-2556-11e9-97fe-ba8918567fd5.png)

Also here is bug info from Sentry.
