### ISSUE TITLE
Bug introduced when added support for django 2.0

### ISSUE THREAD

**Issue by Ashish-Bansal** [noripyt/django-cachalot#118]
Hi,

While trying to port our codebase to django 2.0, we found that django-cachalot has a bug causing our tests to fail. Here's the stacktrace: 
```
Traceback (most recent call last):
  File "/home/vagrant/foobar/foobar/foobar/tests/test_user_filter.py", line 58, in test_get_users_returns_no_duplicates
    self.assertEqual(len(list(users)), len(set(users)))
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 32, in inner
    return original(compiler, *args, **kwargs)
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 79, in inner
    table_cache_keys = _get_table_cache_keys(compiler)
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/cachalot/utils.py", line 188, in _get_table_cache_keys
    for t in _get_tables(db_alias, compiler.query)]
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/cachalot/utils.py", line 165, in _get_tables
    tables.update(_get_tables(db_alias, subquery))
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/cachalot/utils.py", line 164, in _get_tables
    for subquery in _find_subqueries_in_where(query.where.children):
  File "/home/vagrant/foobar/venv/lib/python3.6/site-packages/cachalot/utils.py", line 113, in _find_subqueries_in_where
    rhs = child.rhs
AttributeError: 'NothingNode' object has no attribute 'rhs'
```

I checked the code and found that this change was made into it: 

https://github.com/noripyt/django-cachalot/commit/74e000b8e2b7f4cf9f31319a83d21620ea7b747d#diff-03ee708d723407a4885ffe5b0b8083b6L118

I don't have much idea but it seems like `NothingNode` could be inserted by django in the where's children[0]. So, above line change should be reverted to handle this case.

Looking forward to its fix.

Thanks!  

[0] https://github.com/django/django/blob/6010da2fbda5eee76b6ec586112561dd26b650e8/django/db/models/sql/query.py#L1555

**Comment by calina-c** [comment]
I have the same issue.

**Comment by jakob-kellner** [comment]
Probably the same issue with Django 2.1.12, django-cachalot 2.1.0 and Python 3.6.8

```
...
sh_users/views.py:289: in user_edit
    form.save()
sh_users/forms.py:408: in save
    instance = super().save(*args, **kwargs)
ENV/lib/python3.6/site-packages/django/forms/models.py:459: in save
    self._save_m2m()
ENV/lib/python3.6/site-packages/django/forms/models.py:441: in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
ENV/lib/python3.6/site-packages/django/db/models/fields/related.py:1616: in save_form_data
    getattr(instance, self.attname).set(data)
ENV/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py:975: in set
    objs = tuple(objs)
ENV/lib/python3.6/site-packages/django/db/models/query.py:268: in __iter__
    self._fetch_all()
ENV/lib/python3.6/site-packages/django/db/models/query.py:1186: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
ENV/lib/python3.6/site-packages/django/db/models/query.py:54: in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
ENV/lib/python3.6/site-packages/cachalot/monkey_patch.py:32: in inner
    return original(compiler, *args, **kwargs)
ENV/lib/python3.6/site-packages/cachalot/monkey_patch.py:79: in inner
    table_cache_keys = _get_table_cache_keys(compiler)
ENV/lib/python3.6/site-packages/cachalot/utils.py:187: in _get_table_cache_keys
    for t in _get_tables(db_alias, compiler.query)]
ENV/lib/python3.6/site-packages/cachalot/utils.py:163: in _get_tables
    for subquery in _find_subqueries_in_where(query.where.children):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

children = [<django.db.models.lookups.Exact object at 0x7efdfb239e10>, <django.db.models.fields.related_lookups.RelatedExact object at 0x7efdfb239b00>, <django.db.models.sql.where.NothingNode object at 0x7efdfb243080>]

    def _find_subqueries_in_where(children):
        for child in children:
            child_class = child.__class__
            if child_class is WhereNode:
                for grand_child in _find_subqueries_in_where(child.children):
                    yield grand_child
            elif child_class is ExtraWhere:
                raise IsRawQuery
            else:
>               rhs = child.rhs
E               AttributeError: 'NothingNode' object has no attribute 'rhs'

ENV/lib/python3.6/site-packages/cachalot/utils.py:112: AttributeError

```

**Comment by Andrew-Chen-Wang** [comment]
Should have been fixed
