### ISSUE TITLE
AttributeError: 'ExtraJoinRestriction' object has no attribute 'rhs'

### ISSUE THREAD

**Issue by kennir** [noripyt/django-cachalot#121]
Hi 
I got error below:

```
Traceback (most recent call last):
  File "/Users/ken/Developer/projects/2018/parenting-service/library/tests.py", line 79, in test_smart_album
    self.assertEqual(stories.count(), samples.count())
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/django/db/models/query.py", line 387, in count
    return self.query.get_count(using=self.db)
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/django/db/models/sql/query.py", line 491, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/django/db/models/sql/query.py", line 476, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 32, in inner
    return original(compiler, *args, **kwargs)
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 79, in inner
    table_cache_keys = _get_table_cache_keys(compiler)
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/cachalot/utils.py", line 187, in _get_table_cache_keys
    for t in _get_tables(db_alias, compiler.query)]
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/cachalot/utils.py", line 164, in _get_tables
    tables.update(_get_tables(db_alias, subquery))
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/cachalot/utils.py", line 163, in _get_tables
    for subquery in _find_subqueries_in_where(query.where.children):
  File "/Users/ken/Developer/projects/2018/parenting-service/.direnv/python-3.6.1/lib/python3.6/site-packages/cachalot/utils.py", line 112, in _find_subqueries_in_where
    rhs = child.rhs
AttributeError: 'ExtraJoinRestriction' object has no attribute 'rhs'
```

the queryset sql is 

```
SELECT "library_story"."id", "library_story"."difficulty", "library_story"."title", "library_story"."album_id", "library_story"."position", "library_story"."author", "library_story"."media", "library_story"."cover", "library_story"."cover_cropping", "library_story"."updated_at", "library_story"."created_at" FROM "library_story" WHERE NOT ("library_story"."id" IN (SELECT V1."object_id" FROM "taggit_taggeditem" V1 WHERE (V1."tag_id" IN (SELECT U0."id" FROM "taggit_tag" U0 INNER JOIN "library_smartalbumtagfilter_tags" U1 ON (U0."id" = U1."tag_id") WHERE U1."smartalbumtagfilter_id" = 2) AND V1."content_type_id" = 26))) ORDER BY "library_story"."created_at" DESC
```

any idea ? 

I found ExtraJoinRestriction in the package [taggit](https://github.com/alex/django-taggit/blob/master/taggit/managers.py)

**Comment by BertrandBordage** [comment]
Interesting… I’m not sure how we can deal with ORM extensions like this. I guess the safest solution is to check that `child` is an instance of a known class, otherwise we do not try to cache it.
I keep it as a bug for now, though it’s not technically django-cachalot bug.

**Comment by Andrew-Chen-Wang** [comment]
If it was #132 that fixed it, then it should be patched.
